---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: gitops
  namespace: application-samples
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  type: GitHub
  pathname: https://github.com/luigiaparicio/application-samples.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: gitops-fleet-samples
  namespace: big-bang
spec:
  pathname: https://github.com/luigiaparicio/gitops-fleet-samples.git
  type: Git
