apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pacman-sample
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placementrule
        name: pacman-placement
        requeueAfterSeconds: 30
  template: 
    # This is a template Argo CD Application, but with support for parameter substitution.
    metadata:
      name: 'pacman-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/luigiaparicio/application-samples.git
        targetRevision: main
        path: pacman
      destination:
        server: '{{server}}'
        namespace: pacman
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: pacman-placement
  namespace: openshift-gitops
spec:
  clusterReplicas: 1   # Availability choice, maximum number of clusters to provision at once
  clusterSelector:
    matchLabels:
      'usage': 'lab'
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
