---
apiVersion: v1                      
kind: Namespace
metadata:
  name: ggithubcom-luigiaparicio-clusterclaims-controller-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: low
  name: ggithubcom-luigiaparicio-clusterclaims-controller
  namespace: ggithubcom-luigiaparicio-clusterclaims-controller-ns
spec:
  type: Git
  pathname: 'https://github.com/luigiaparicio/clusterclaims-controller.git'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: deploy
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: clusterclaims-controller
  name: clusterclaims-controller-subscription-1
  namespace: open-cluster-management
spec:
  channel: ggithubcom-luigiaparicio-clusterclaims-controller-ns/ggithubcom-luigiaparicio-clusterclaims-controller
  placement:
    placementRef:
      kind: PlacementRule
      name: clusterclaims-controller-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: clusterclaims-controller
  name: clusterclaims-controller-placement-1
  namespace: open-cluster-management
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'
